### ISSUE TITLE
supporting PGP/MIME format?

### ISSUE THREAD

**Issue by winnie-chaintope** [jerson/flutter-openpgp#10]
<img width="544" alt="Screenshot 2020-10-01 at 10 06 47 AM" src="https://user-images.githubusercontent.com/61957420/94757768-d6b07680-03cd-11eb-86cf-576606fc4a6c.png">

the output of Encrypt method looks like just a PGP encrypted result
`await OpenPGP.encrypt("text","[publicKey here]")`

does this package support return in PGP/MIME format?

**Comment by jerson** [comment]
right now no, but i think is something i can add it too,  after finish the refactor with bindings

i have a question about that:
What are the use cases for using this format?

**Comment by jerson** [comment]
cc @winnie-chaintope

**Comment by winnie-chaintope** [comment]
thanks for the fast response.
it is use for email encryption, for a more safe file transfer.

I will closed this issue for now.
Thanks
