### ISSUE TITLE
gpg-tools not supported?

### ISSUE THREAD

**Issue by winnie-chaintope** [jerson/flutter-openpgp#13]
i encrypted a zip file using `await OpenPGP.encryptBytes(bytes, 'pubkey')` when i decrypt the file using gpg-tools it gives this error 
<img width="375" alt="Screenshot 2020-11-04 at 5 07 42 PM" src="https://user-images.githubusercontent.com/61957420/98091688-b5591380-1ec0-11eb-8e2f-a63fdfe0b6d7.png">

if decrypt using `await OpenPGP.encryptBytes()` have no issue

**Comment by jerson** [comment]
hi @winnie-chaintope  thanks for report the issue, could be related to ciphers of gpg-tools but i gonna check with that tool, so please if you could share an example and upload the encrypted file would be great, thank you.

**Comment by winnie-chaintope** [comment]
i recreated a sample zip file. this time i got a diffrent error from the gpg tools
<img width="372" alt="Screenshot 2020-11-05 at 10 11 14 AM" src="https://user-images.githubusercontent.com/61957420/98189112-42e34480-1f4f-11eb-8146-1c7869bf3098.png">

my sample files
[sample_zip.zip](https://github.com/jerson/flutter-openpgp/files/5491470/sample_zip.zip)
[sample_zip(encrypted with package, decrypted with pgp tools).zip](https://github.com/jerson/flutter-openpgp/files/5491473/sample_zip.encrypted.with.package.decrypted.with.pgp.tools.zip)

this is something i found out when i comparing the uint8list of both zip files
left hand side is the original zip file's uint8list, right hand side is after encrypted with package and decrypted with pgp tools
looks like there is some missing bytes '13'. wondering it could be missing something from encryption.
fyi, my sample zip file contains japanese if that could be an issue

<img width="1196" alt="Screenshot 2020-11-05 at 10 00 45 AM" src="https://user-images.githubusercontent.com/61957420/98188652-635ecf00-1f4e-11eb-9f3a-30803fbaf152.png">

**Comment by jerson** [comment]
thank you for that, also it's important to know which version are you using? 1.0.0-rc1 or 0.9.9

**Comment by winnie-chaintope** [comment]
1.0.0-rc1

**Comment by winnie-chaintope** [comment]
additional info: 
i tested with a zip file
`String data = createMimeMessage(zipFile)` //create mime format of string type
and encrypt with 
`await OpenPGP.encrypt(data, pubKey)`
i return file in format of _'encrypted.eml.gpg'_
it can success decrypt using gpg tools and return _'encrypted.eml'_
i can manage to open the zip file inside my .eml file

**Comment by jerson** [comment]
news: i found the issue, so probably these days im gonna release a new rc version, when the new version will be releases im gonna update this issue, thank you :D

**Comment by jerson** [comment]
hi @winnie-chaintope new version was released https://pub.dev/packages/openpgp/versions/1.0.0-rc2, so if you could help me testing with that version would be great,

but there is a small change on encrypt, now is needed add a FileHint and should looks like this
```dart

    var encrypted = await OpenPGP.encryptBytes(
      input.readAsBytesSync(),
      widget.keyPair.publicKey,
      fileHints: FileHints()..isBinary = true,
    );
```

FileHints contains more options, when you want to set as a binary, the reason for use a new option is because im using go crypto implementation and they use same struct,

if you have some questions or need some help please let me know.

**Comment by winnie-chaintope** [comment]
hi @jerson, i tested it can work with zip file now 
thanks so much for the quick fixed
