### ISSUE TITLE
Linux setup instructions outdated

### ISSUE THREAD

**Issue by TheOneWithTheBraid** [jerson/flutter-openpgp#14]
The instructions for the Linux setup seem to be pretty old. Could you provide new ones?

Currently, the referenced `linux/app_configuration.mk` file is no longer used and though the plugin no longer works for Linux throwing a `MissingPluginException`...

Anyway, thank you for this great plugin!

**Comment by jerson** [comment]
Hi @TheOneWithTheBraid for linux you should use version 1.0.0-rc1 which not require any additional changes to work
https://pub.dev/packages/openpgp/versions/1.0.0-rc1
