### ISSUE TITLE
Implement PublicKey and PrivateKey classes supporting metadata, fingerprint etc.

### ISSUE THREAD

**Issue by TheOneWithTheBraid** [jerson/flutter-openpgp#16]
It would be great to see classes for both public and private keys the following way:

```dart
abstract class Key {
Key formArmored(String key);
Key formBinary(Uint8List key);
}

class PublicKey extends Key {
}

class PrivateKey extends {
}
```

This is necessary for basic PGP functions like determination of key's name, address, expiry and fingerprint.

In the future, methods for generating revocation certificates and export to armored / binary keys.

Thank you very much for this package.

**Comment by jerson** [comment]
Hi @TheOneWithTheBraid sorry for the delay, and yes would be nice to have those methods, right now im very busy at work, sadly currenty in working more in Golang so I dont have enoght time to touch dart code

**Comment by jerson** [comment]
Hi has been a while, but finally i got some time to implement this, probably you dont need this anymore, but for the record here is the version https://pub.dev/packages/openpgp/versions/3.3.0#metadata-methods
