### ISSUE TITLE
make and signing

### ISSUE THREAD

**Issue by joe-getcouragenow** [jerson/flutter-openpgp#17]
@jerson 

Regarding the CI builds.  
 I am working on a mage based system which uses the same code to build the golang and flutter stuff locally and in github workflows. Its maybe 80% done. Will let you know when its ready for trying out.     Its a mess right now as i have had to work on other stuff.
Then there is one way to build for local and ci, and its 100% golang driven.

I am also working on signing for all of the binaries also.
Have not cracked yet how to sign the go-flutter DMG and MSI yet.  it will be integrated into the mage file and so do it automatically. 
For Apple i am using this: https://github.com/mitchellh/gon

Let me know your thoughts....

**Comment by jerson** [comment]
sound very interesting i never used a tool like that, but he did a great job with that library, when this will be on a ci environment this looks very helpful, I have more experience with mobile applications and there the signatures are more integrated I would say, so I never had to use something like that
