### ISSUE TITLE
pgrok

### ISSUE THREAD

**Issue by joe-getcouragenow** [jerson/flutter-openpgp#18]
You dont have Issues setup on the pgrok repo, so am writing the issue here if you dont mind..

I have forked pgrok so i can PR some changes. 

1.  Gateway . Add LetsEncrypt for the Server so the Certs are gotten at runtime. Will be a wildcard cert.
- will be saved on file system and later in an encrypted DB

2. Client
- Auth token from the client sent to the server. If the auth token and subdomain matchup up the Server gateway will return to the Client the Certs.

is that useful for you too ?

**Comment by jerson** [comment]
@joe-getcouragenow  Yeah absolutely this would help a lot to me, i was thinking on use acme to use dns challenge to get wildcard certs, but i didnt have time for that, thanks you for that

**Comment by jerson** [comment]
and for pgrok i dont have any issue with setup, im using a custom tap, with the same github release assets 

https://github.com/jerson/homebrew-tap/blob/master/Formula/pgrok.rb
https://github.com/jerson/homebrew-tap/blob/master/Formula/pgrokd.rb
