### ISSUE TITLE
OpenpgpPlugin not instantiating properly on android

### ISSUE THREAD

**Issue by irasekh3** [jerson/flutter-openpgp#2]
It seems that the example you wrote is triggering `onAttachedToEngine` when instantiating and registering the OpenpgpPlugin. However, I am working on an app that seems to be registering the plugin with the `registerWith`.  Unfortunately it seems that `registerWith` is not properly instantiating
`private FastOpenPGP instance;` or `private Handler handler;`.

When I do run the plugin as it stands today and try to generate a key pair I get the following nullpointer exception:

``` java
E/AndroidRuntime( 5642): FATAL EXCEPTION: Thread-3
E/AndroidRuntime( 5642): Process: com.example.app, PID: 5642
E/AndroidRuntime( 5642): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Handler.post(java.lang.Runnable)' on a null object reference
E/AndroidRuntime( 5642): 	at dev.jerson.openpgp.OpenpgpPlugin.error(OpenpgpPlugin.java:146)
E/AndroidRuntime( 5642): 	at dev.jerson.openpgp.OpenpgpPlugin.access$200(OpenpgpPlugin.java:26)
E/AndroidRuntime( 5642): 	at dev.jerson.openpgp.OpenpgpPlugin$9.run(OpenpgpPlugin.java:295)
E/AndroidRuntime( 5642): 	at java.lang.Thread.run(Thread.java:919)
I/Process ( 5642): Sending signal. PID: 5642 SIG: 9
Lost connection to device.
Exited (sigterm)
```

**Comment by jerson** [comment]
thanks @irasekh3 im going to implement the missing part with registerWith

**Comment by jerson** [comment]
thanks @irasekh3  now is merged and released 

https://pub.dev/packages/openpgp/versions/0.8.2
