### ISSUE TITLE
Incorrect location of libopenpgp_bridge.so on Linux platform

### ISSUE THREAD

**Issue by ryans233** [jerson/flutter-openpgp#28]
Hi!
I tried the plugin recently and it works flawlessly on Windows. However when I try to build a project which depends on flutter-openpgp on Linux, the location of libopenpgp_bridge.so seems to be incorrect.
In my case I cannot find out libopenpgp_bridge.so in `${PROJECT_NAME}/build/linux/x64/${BUILD_FLAVOR}/bundle/lib/` with both debug and release build, thus getting `flutter: Invalid argument(s): Failed to load dynamic library 'libopenpgp_bridge.so': libopenpgp_bridge.so: cannot open shared object file: No such file or directory` output on debug console. Then I found that file at `${PROJECT_NAME}/build/linux/x64/${BUILD_FLAVOR}/plugins/openpgp/bundle/lib/` and copy it to the first one, letting openpgp back to work.
Could you please make a fix? So that we don't need to move that file manually every time.
Thanks.

**Comment by jerson** [comment]
Hi @ryans233 thanks for report the issue, I will check that next week, bc this week im on vacation

**Comment by ryans233** [comment]
Thanks! Have a great vacation!

**Comment by jerson** [comment]
hey @ryans233 I just released a new version with the fix for that, please take a look https://pub.dev/packages/openpgp/versions/3.1.1 

tested here and seems works fine.

commit: https://github.com/jerson/flutter-openpgp/commit/1baab646721a11f24c36120027805a0980339f77

**Comment by jerson** [comment]
im gonna close this ticket but if you feel that is not fixed yet please reopen it
