### ISSUE TITLE
Possible to load external public, private keys and signatures?

### ISSUE THREAD

**Issue by KlausQalmari** [jerson/flutter-openpgp#31]
Hi there,

Is it possible to load external public, private keys, and signatures?

For example, if I export my public key:
`gpg --output public.pgp --armor --export test@test.com`  
Sign document:
`gpg --detach-sign config.json`

How could I use these with your package?

Thanks!

**Comment by jerson** [comment]
Hi @KlausQalmari please see example directory there are some examples

https://github.com/jerson/flutter-openpgp/tree/master/example
