### ISSUE TITLE
Unhandled Exception: type 'List<dynamic>' is not a subtype of type 'FutureOr<Uint8List>?'

### ISSUE THREAD

**Issue by eli1stark** [jerson/flutter-openpgp#33]
Sample code: `OpenPGP.encrypt('data', 'key')`
This code throws `Unhandled Exception: type 'List<dynamic>' is not a subtype of type 'FutureOr<Uint8List>?'`

openpgp: ^3.2.6

**Comment by jerson** [comment]
Hi @eli1stark thanks for report the issue, is this happening on simulator ios or in a real device?

**Comment by eli1stark** [comment]
Both

**Comment by Gabriel-Azevedo** [comment]
Hi @jerson 

I'm getting the same error but different from eli2start I only have one golang (yours) package in my project. We are using your package to encrypt credit card data so it's highly important for us. 

Do you have any quick fixes we can try? I didn't understand what was your suggestion in the previous comment. Could you elaborate more?

Really appreciate the help.

**Comment by jerson** [comment]
Hi @Gabriel-Azevedo which version are you using?

**Comment by jerson** [comment]
@Gabriel-Azevedo just released a new version without the objcopy renaming stuffs, so probably that will work for you

```yaml
openpgp: ^3.2.7
```
