### ISSUE TITLE
Getting null on binaryMessenger.send() method

### ISSUE THREAD

**Issue by jaimik11** [jerson/flutter-openpgp#35]
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method encrypt on channel openpgp)

**Comment by jerson** [comment]
Hi @jaimik11 thanks for report the issue, could you share you `flutter doctor`, which flutter version, which library version, and in which arch and OS are you trying to run this library?

and if you have an example how you are calling that method will be great.
