### ISSUE TITLE
Unhandled Exception: type '_List<dynamic>' is not a subtype of type 'FutureOr<Uint8List>?' 

### ISSUE THREAD

**Issue by Hardik3143** [jerson/flutter-openpgp#37]
I am getting this error in release mode  in Flutter + IOS

**Comment by jerson** [comment]
hi @Hardik3143 thanks for report the issue, could you give more details please, `flutter doctor` output and which version of this library are you using?

**Comment by Hardik3143** [comment]
Flutter Doctor Output : 
----------------------------------------------------------

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.3, on macOS 12.3.1 21E258 darwin-arm, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!


And also i am using this library version : openpgp: ^3.2.8

**Comment by jerson** [comment]
Hi maybe is too late but try with this version https://pub.dev/packages/openpgp/versions/3.4.3
I'm gonna close this issue but feel free to reopen
