### ISSUE TITLE
[Question] Get public key from private key?

### ISSUE THREAD

**Issue by Myzel394** [jerson/flutter-openpgp#40]
Can you obtain the public key from the private key? OpenPGP's Javascript version has this functionality, but doesn't seem like it's implemented here.

**Comment by jerson** [comment]
Hi @Myzel394 yeah, you can do it using

```
OpenPGP.convertPrivateKeyToPublicKey("[privateKey
```

**Comment by Myzel394** [comment]
@jerson Thank you, I also just found it in the docs 😆 thought "Convert methods" were methods for type conversions :D
