### ISSUE TITLE
Crash in readPrivateKeys when the input contains both public and private keys

### ISSUE THREAD

**Issue by tallinn1960** [jerson/flutter-openpgp#42]
Is it correct that the current version of openpgp, 3.4.0, does not support DSA/ElGamal keys, but RSA keys only?

As openpgp is crashing within the go code in

* thread #43, name = 'DartWorker', stop reason = EXC_BAD_ACCESS (code=1, address=0xe0)
    frame #0: 0x00000001049e50cc Runner`github.com/jerson/openpgp-mobile/openpgp.(*FastOpenPGP).readPrivateKeys + 124
Runner`github.com/jerson/openpgp-mobile/openpgp.(*FastOpenPGP).readPrivateKeys:
->  0x1049e50cc <+124>: ldrb   w6, [x6, #0xe0]
    0x1049e50d0 <+128>: cbz    x6, 0x1049e50b8           ; <+104>
    0x1049e50d4 <+132>: str    x3, [sp, #0x60]
    0x1049e50d8 <+136>: str    x5, [sp, #0x78]

(this is on iOS)

when asked to decypt a cryptotext with a DSA/Elgamal key.

**Comment by jerson** [comment]
Hi @tallinn1960 yeah you are right currently we only support RSA but Im gonna start doing a research to include more, it May require some extra time but I will notify you when that become implemented

**Comment by tallinn1960** [comment]
Well, it turned out that not the key algorithm was the problem, but the mix of private and public keys in the string I gave to a verify operation. I changed the subject here accordingly. 

And now suprisingly the test I wrote using a DSA/ElGamal-Key for decryption worked and produced plaintext. So there is support for those keys.
