### ISSUE TITLE
Example code has use of insecure parameters

### ISSUE THREAD

**Issue by vanitasvitae** [jerson/flutter-openpgp#44]
Hey,
the README shows the use of 1024 bits RSA keys:
```
var keyOptions = KeyOptions()..rsaBits = 1024;
```

1024 is very weak and should be avoided. Most authorities recommend use of at least 2048, better 3072, see https://www.keylength.com/en/

**Comment by jerson** [comment]
thanks @vanitasvitae I just updated readme
