### ISSUE TITLE
There seems to be now way to obtain the user-id of an ascii-armored key?

### ISSUE THREAD

**Issue by tallinn1960** [jerson/flutter-openpgp#45]
I am searching in the API for way to obtain the user-id of the key, which is most often the e-mail adress the key is used with. 

I can't find a field user_id in the MetaData for public and private keys.

Am I missing something?

**Comment by jerson** [comment]
Hi @tallinn1960 yeah thats true, we should need to add more properties to getPrivateKeyMetadata, I think this weekend I can make a research on that

**Comment by tallinn1960** [comment]
The user-id is needed in both Public and PrivateMetaData. Thank you for looking into it. I want to get pgp int Maily. (https://github.com/Enough-Software/enough_mail_app.git <https://github.com/Enough-Software/enough_mail_app.git>) And so far your plugin is easy to use, but this is an issue.

Thanks,
Olaf

**Comment by jerson** [comment]
Hi @tallinn1960 , please try again using latest vesion v3.4.2 there is a new property named: identities
ref: https://pub.dev/packages/openpgp/versions/3.4.2
![image](https://user-images.githubusercontent.com/325780/189453350-aaff0473-3dc5-49c3-8173-020b28f7bab9.png)

**Comment by tallinn1960** [comment]
That looks very good! That is exactly, what’s needed.
Thank you so far.
