### ISSUE TITLE
Wrong architecture of libopenpgp_bridge.so on ARM64 device

### ISSUE THREAD

**Issue by MrCyjaneK** [jerson/flutter-openpgp#49]
I'm developing an app on a arm64 device (armbian: `Linux x 6.1.10-rockchip64 #trunk.0242 SMP PREEMPT Tue Feb  7 05:24:35 UTC 2023 aarch64 GNU/Linux`)

I'm unable to produce a working working executable in both debug and release builds because of libopenpgp_bridge.so being compiled for wrong architecture.

```plain
$ file build/linux/arm64/*/bundle/lib/*.so 
build/linux/arm64/debug/bundle/lib/libflutter_linux_gtk.so:   ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, BuildID[sha1]=a072b72ecc95306735daaad5b47c620b4953f556, stripped
build/linux/arm64/debug/bundle/lib/libopenpgp_bridge.so:      ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=adcb9def550a7eaa9e488621a31e6854ca2e23d6, stripped
build/linux/arm64/debug/bundle/lib/libopenpgp_plugin.so:      ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, BuildID[sha1]=16f0668d18c65ce9d4b1fb36d32c90c8bba671a0, with debug_info, not stripped
build/linux/arm64/release/bundle/lib/libapp.so:               ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, BuildID[md5/uuid]=8228d9e1c0f9f4ff3c2a23c0dff94fb0, stripped
build/linux/arm64/release/bundle/lib/libflutter_linux_gtk.so: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, BuildID[sha1]=50790af499eb625dd98554b310f0cdd5d3005e38, stripped
build/linux/arm64/release/bundle/lib/libopenpgp_bridge.so:    ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=adcb9def550a7eaa9e488621a31e6854ca2e23d6, stripped
build/linux/arm64/release/bundle/lib/libopenpgp_plugin.so:    ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, BuildID[sha1]=def16c5db18326d5eb75304b3874cb53cfaa69ae, not stripped
```

I guess that it have something to do with `~/.pub-cache/hosted/pub.dev/openpgp-3.5.1/linux/shared/libopenpgp_bridge.so` also being x86_64 binary instead of arm64.

**Comment by jerson** [comment]
Hi @MrCyjaneK, thanks for report this issue, yeah for linux I only added x86_64 but I think I can include arm64 binaries, could you try replacing the .so by the arm64 version from https://github.com/jerson/openpgp-mobile/releases/download/v1.7.0/libopenpgp_bridge_linux_v1.7.0.tar.gz to be sure that only that change is needed

**Comment by jerson** [comment]
and just by curiosity which linux device are you using? is a rockpro64 or a pinebook pro?

**Comment by jerson** [comment]
Hi, I just send a new PR about this https://github.com/jerson/flutter-openpgp/pull/50

**Comment by jerson** [comment]
New version released https://pub.dev/packages/openpgp/versions/3.5.3 please try with this one, feel free to reopen the issue if its needed

**Comment by MrCyjaneK** [comment]
Hey @jerson! I am not able to reopen this but I have new issue:

Currently it fails with following error:

```plain
CMake Error at cmake_install.cmake:148 (file):
  file INSTALL cannot find
  ".../project/linux/flutter/ephemeral/.plugin_symlinks/openpgp/linux/shared/aarch64/libopenpgp_bridge.so":
  No such file or directory
```

However after moving arm64 directory into aarch64 it worked just fine:

```plain
$ mv project/linux/flutter/ephemeral/.plugin_symlinks/openpgp/linux/shared/arm64 project/linux/flutter/ephemeral/.plugin_symlinks/openpgp/linux/shared/aarch64
```

**Comment by jerson** [comment]
Hi @MrCyjaneK thanks for report this, I think is easy to fix, im going to be fixing this in the next release

**Comment by jerson** [comment]
Hi   @MrCyjaneK  I just released a new version, please take a look, this time should be fine

https://pub.dev/packages/openpgp/versions/3.5.4
