### ISSUE TITLE
Android APK contains other Abi versions

### ISSUE THREAD

**Issue by Myzel394** [jerson/flutter-openpgp#57]
After realizing an apk built using `flutter build apk --target-platform android-x64`, it contains all Abi versions of openpgp.

In there a way to only the use targeted one? This would reduce the APK size a lot.

**Comment by jerson** [comment]
Hi @Myzel394 thanks for report this, I'm not sure how target platform works in flutter, but yeah by default all folders are added, I'm going to look what should be modified in order to only pick the right file

**Comment by jerson** [comment]
for future references: `flutter build apk --target-platform android-x64 --split-per-abi`
