### ISSUE TITLE
Signing with only private key

### ISSUE THREAD

**Issue by ccprogrammer** [jerson/flutter-openpgp#60]
i want to sign a message with only private key without public key and passphrase, how do you achieve this ?

**Comment by jerson** [comment]
Hey @ccprogrammer thanks for report this, you could use this method to extract the public key from the private key

```dart
 var result = await OpenPGP.convertPrivateKeyToPublicKey("[privateKey here]");
```

**Comment by ccprogrammer** [comment]
but how do you do the sign? the function still need private,public, and passphrase

**Comment by jerson** [comment]
yeah, you can leave passphrase as empty if there are no passphrase, privateKey is required and public key is something we could remove in future versions

**Comment by ccprogrammer** [comment]
Thank you for replying, im doing it like this am i correct? because i want to sign a message with only private key then i extract the public key from private key and insert it to the sign method, it works fine but i doubt im doing it correctly. Btw im with opensort  

```dart
     var _pubKey = await OpenPGP.convertPrivateKeyToPublicKey(privateKey);
      final _mapping = {
        "address": address,
        "pub": publicKey,
        "type": "member",
      };
      _csr = await OpenPGP.sign(_mapping.toString(), _pubKey, privateKey, '');
```

**Comment by jerson** [comment]
Yes this is the current way to do it (not very handy but the current way), it seems that extra publicKey can be removed from the required args, so I'll probably do that in the next release

**Comment by ccprogrammer** [comment]
okay thanks
