### ISSUE TITLE
armorDecode or something

### ISSUE THREAD

**Issue by michep** [jerson/flutter-openpgp#62]
Hello,

I have to encode and later - decode a binary file into and from armored (ASCII) message format.

For encoding I do:
```
Future<String?> encryptBinary(Uint8List data) async {
    var encoded = await OpenPGP.encryptBytes(data, pubKey);
    return OpenPGP.armorEncode(encoded);
}
```

But for decoding a String into binary ther is no way - there is no `armorDecode()` function or something.

Is there any way I can do it?

**Comment by jerson** [comment]
amorDecode was introduced in v3.7.1, there is a new function signature for encode as well, allowing set a different message type

```dart

    var armorEncoded = await OpenPGP.armorEncode("PGP MESSAGE", bytesSample);
    var result = await OpenPGP.armorDecode(armorEncoded);

```

for now I'm closing this issue, but feel free to open if something is not working as expected
