### ISSUE TITLE
change in OpenPGP.encrypt() that makes message invalid in other libs

### ISSUE THREAD

**Issue by michep** [jerson/flutter-openpgp#63]
Hello.

I have an application that encodes string data with OpenPGP.encrypt() method. And up until version3.7.0 all other pgp clients that were tried to decrypt messages were doing it OK - no any issues with that.
But after I've updated to versions 3.7.0 other libraries started to report "Not a valid PGP Message" on every encrypted message hat i've sent.

And there is a visible difference in armored ecrypted messages:

OpenPGP.encrypt("hello", pubkey1 + "\n" + pubkey2);

Prior to 3.7.0 it gives:

"-----BEGIN PGP MESSAGE-----
Version: openpgp-mobile

wcBMA/Qt1M8IXRJkAQgAqN5D+8SrZodNECPu5fiTwFE26yjx7pMoNHn1I6cWhC8P
dI1iegjIEAeAsr5RGT8eOj+ExWN71ZK9CU7fvpXnmd9wx0PaGC/PkD2jL/t92pko
riDPbFy1DwFyT/c/Xlx78we97WVgYSAutZ//lt/Q7iNCgxaJmB0KvJbyze9AtRdr
Ng3i1XFGQCAveF7VS4Gk7I8o0IPeLK5jrLqC0Cizj2ykVHtp+CTw53iiFpwZXgcT
hiB/9ZDV20lpuDh19srUul8KS/F039s7mGvLVimgParbk6qRF/lRZDSiGkz9Ee5Z
GL1LeN48OOpHJmjEFUFktio6tNzHl3ow8SJ/MbESH8HATANngF/qmr8TZgEIAK7x
Eyr6NFOrRaCwKSPpuknczP9X0rZ0gwxA3MccAgyREE+KtHED4XckTqUYqN0LXun2
vLkhdvh3xydWTYjQJGfjbhg5l8vhDbqANPIvX8jxxcGaUglCJPtnHhkJjS9kjnQT
G98bIAh/f4I8Vv9jTFoLcTFv8L5w2u2p0sFZrKAn5MOIPkPHihIYol7pZWCvdBbH
kxRzT1faf5++6pzHaAHnZVySz3GfTDlhdKfdRjrbiPy+jv3fASRBuT8EsW5EaCsC
VJKKouCUcNqK+mrVO5DTvWpgz8GVDml3q0gdlqCDtv2S1kaYXtFCHdFRNtGMm+zF
4MXdQR5l4ahIZVV+mlzSNgHtbNMH6zAn24omKMUVurJ5KcSNsZymTNQzV7ddI2fi
9VQPJ+NSOB1P9d/6Bf/6rK5nT4exDw==
=C5On
-----END PGP MESSAGE-----"

But on 3.7.0 it gives:

"-----BEGIN PGP MESSAGE-----
Version: openpgp-mobile

wcBMA/Qt1M8IXRJkAQf+JkKqRvOtBLi5KvONkK9Lpq44CM08K5ifartmwGpBsDWc
e5mlOf1W64wjuiW0g8w5xBwPzrvK8oFm0hzLpt3ombjtj8Bg9yFVlx9Mn5gTnUR9
J+VTo1qQd5u6eMLgMoRdRjLH6CHtUCvTmwyrRTjzZBl7QO6ej9RK5EA/vTYFhaUZ
u3bFQFMoHmajhbCumyrmv3TNKmbVgKizVxMC4aQvGa5Ry7YDO0XS7fnfsSAwFbN5
gKqEMKFLouOG4OpcVHeXNVIlM5gE9vQ7pj/0YWxTaNioAd0HrH3CyMAI7hKyOgeb
TgF1j737OWNKlJXLBs8Yw6s5hjNJQt+XilZPbfDQ6MHATANngF/qmr8TZgEH/iP7
IPPlLm2fAeEQtaPppEQlz3ETlxk6UsW/uUZaddzrbcmb+y8rplZIUw7ZAV8xySgy
q+37nhxwE/tBOrwQasqn1gc6jthzaSKUQwZ2SOJNv70Q0+uxGG5dARPN2EklUGiZ
9rWAI/j8kfHnU9J4xiQFMroomK9LKRUjy/tgifv8cwkbnN+CyWW8wx0uAbcX6k+m
f4ZJvTDYbxihxMkXDLm1xcKfb/o507Uvec0W4BNdrdgQB9GuoRUo/ToVL4bNIy3p
KSsbTuEG0wCfzjRCftq8ePnRXb2RJGpQwWCEptgDW5ZmkwRr9OBl4egUrR8PODPy
4JvzBf470x+CYBA3XFHSNgFLZt6FkSgMdmFj69Ptz1jHP9K1GUNToe7/z6he8ShE
m4Ibw1ojRTMgGauK9TKO0+ptzocdOA==
-----END PGP MESSAGE-----"

I can see this "=C5On" suffix in the first one, which is absent in the second.

**Comment by jerson** [comment]
Hi @michep thanks for report this, the change I did was update the go dependency github.com/ProtonMail/go-crypto v0.0.0-20230816083609-9c54acec5c54 I can review maybe there is something to rollback

**Comment by michep** [comment]
Hello @jerson, I can confirm that this commit [armor-fix](https://github.com/jerson/flutter-openpgp/tree/armor-fix) fixes issue with compatibility with other openpgp implementation libs. Thank you for your work and I am looking forward for armorDecode() method :)

**Comment by jerson** [comment]
Thanks for you help, PR was merged and new version v3.7.1 contains the fix + new decode method
