### ISSUE TITLE
decryption give a null value.

### ISSUE THREAD

**Issue by manishrelani** [jerson/flutter-openpgp#9]
flutter: encrypt -----BEGIN PGP MESSAGE-----
Version: fast-openpgp
wcBMA9/efA5kSCbZAQgAClkZi61CJKr4D9R0boaB9LKzIbzfOCLsPIuFzOCZfAeb
p5jGsKgRsO621PafIF/oywVnAgEMGw17EdPv6i5C3Ldw/FspSwh5YvzOmRmiZ8CB
bRwSXKLxTS/4zvX7y3PcwZCnVmIiB/tZHCBhXrvemUSdffzFt+VxbzoY4fG0xHKL
yWKyxbqotMXkOM2/iruFea4D2AVl0kJQKSzv7DYatEnMDf7BkJHY5VTeOipaoT8T
NCsIm3z/F2o88/ZI7rUZxIedB2q7mak29RJYrAti5b/t9iB44EsElO2vIdeEz4/a
BpGdunNiblv1FsABEQARJ981UQA6NcBy/9DajG3EYNLgAeQVTpUf/+UXqLoT3v4D
2T7d4cu84PXg7+E+p+C44kiiACHgEOJDv1SN4OPkOjaqnb26itBpz1j51SiDB+I8
tmn14Ze8AA==
=qbtz
-----END PGP MESSAGE-----
flutter: sign -----BEGIN PGP SIGNATURE-----
Version: fast-openpgp
wsBcBAABCAAQBQJfa1l7CRD1suCFGU4uKQAA3+oIAFILjiVSq6rt4drqUBLk46ey
E+GQn8iAibJN/QicJGmciXjfbSgYgyT8R/rE9y4F/HN70GxugDxTfuzxtkvEzrq+
dnTCwqQzH19hrJXBagqfVte7qdkN6gx5Fk8aoqUNh1XL22mCFD/j0n2CgMGBC2ZV
19Hb2dO/RakYRIsJJkd1C8N7tLSCvoeHiMVXi1+WT3lsxN0dSoQYLHyUrCnvVcFq
9qAihYnmp4RADZ17veXvmULb6kOaoYyYLDNnbFd9itjkpagTTWKI/3xaE0HdTe3R
wr1+OIt2EDFcI8uk2yfbnPDOCljvBPF9LKyp1ZOntSYGB84UyfnXF0ZRUJAd8vE=
=IEcg
-----END PGP SIGNATURE-----
flutter: verify: true
flutter: PlatformException(1, Error Domain=go Code=1 "EOF" UserInfo={NSLocalizedDescription=EOF}, null)
flutter: decrpt null

**Comment by jerson** [comment]
hi @manishrelani thanks for report the issue, please can you add more info, maybe and example so i can reproduce the issue here and look whats going
